# Generated by Django 5.2.12 on 2026-03-14 05:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carniceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carniceria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carnicería',
                'verbose_name_plural': 'Carnicerías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso_media_res', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('porcentaje_carne', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('porcentaje_hueso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('porcentaje_grasa', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_grasa', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carniceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.carniceria')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompraCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('porcentaje_rendimiento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='core.compra')),
            ],
            options={
                'verbose_name': 'Corte de compra',
                'verbose_name_plural': 'Cortes de compra',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('porcentaje_rendimiento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('carniceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='core.carniceria')),
            ],
            options={
                'verbose_name': 'Corte',
                'verbose_name_plural': 'Cortes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('peso_media_res__gt', 0)), name='compra_peso_positivo'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_kg__gt', 0)), name='compra_precio_kg_positivo'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_carne__gt', 0)), name='compra_carne_positiva'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_hueso__gte', 0)), name='compra_hueso_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_grasa__gte', 0)), name='compra_grasa_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_grasa__gte', 0)), name='compra_precio_grasa_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='compracorte',
            constraint=models.UniqueConstraint(fields=('compra', 'nombre'), name='unique_compra_corte_nombre'),
        ),
        migrations.AddConstraint(
            model_name='compracorte',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_rendimiento__gt', 0)), name='compra_corte_rendimiento_positivo'),
        ),
        migrations.AddConstraint(
            model_name='compracorte',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_rendimiento__lte', 100)), name='compra_corte_rendimiento_maximo'),
        ),
        migrations.AddConstraint(
            model_name='compracorte',
            constraint=models.CheckConstraint(condition=models.Q(('margen_porcentaje__gte', 0)), name='compra_corte_margen_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='corte',
            constraint=models.UniqueConstraint(fields=('carniceria', 'nombre'), name='unique_corte_por_carniceria'),
        ),
        migrations.AddConstraint(
            model_name='corte',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_rendimiento__gt', 0)), name='corte_rendimiento_positivo'),
        ),
        migrations.AddConstraint(
            model_name='corte',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_rendimiento__lte', 100)), name='corte_rendimiento_maximo'),
        ),
        migrations.AddConstraint(
            model_name='corte',
            constraint=models.CheckConstraint(condition=models.Q(('margen_porcentaje__gte', 0)), name='corte_margen_no_negativo'),
        ),
    ]
